--Insert na TB Venderores

DECLARE @MATRICULA VARCHAR(5)
DECLARE @NOME VARCHAR(100)
DECLARE @PERCENTUAL FLOAT
DECLARE @DATA DATE
DECLARE @FERIAS BIT
DECLARE @BAIRRO VARCHAR(100)

SET @MATRICULA ='00239'
SET @NOME = 'José Matos'
SET @PERCENTUAL = 0.10
SET @DATA ='20100120'
SET @FERIAS = 1
SET @BAIRRO = 'Meier'

INSERT INTO [TABELA DE VENDEDORES] (MATRICULA,NOME,[PERCENTUAL COMISSÃO],[DATA ADMISSÃO],[DE FERIAS],BAIRRO)
VALUES(
@MATRICULA, @NOME,@PERCENTUAL, @DATA, @FERIAS, @BAIRRO)